name: Berlin VSH Bot

on:
  schedule:
    # Run at 7AM, 10AM, 1PM, 4PM Berlin Time (adjusted for UTC)
    - cron: '0 5-16/3 * * 1-5'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker Image
        run: docker pull lapey/send_vsh_bot:latest

      - name: Run Docker Container
        run: |
          docker run --rm --name vsh-bot \
            -e TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}" \
            -e TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}" \
            lapey/send_vsh_bot:latest

      - name: Logout from Docker Hub
        run: docker logout

      - name: Delete Docker Container
        run: docker rm vsh-bot